### PR TITLE
Correct name

### PR DESCRIPTION
**Pull request by CrazyPython**

### CODE REVIEW

**Review by liamjohnston — APPROVED** [review]
Ha, thx. This project is long dead 💀 

One of these days I'm going to rebuild it in react or something.

**Comment by deanoemcke** [comment]
May as well merge it :)
Long dead eh? Is the office still using it?
I feel like it was one of our most promising ideas. Remember the fooseball days?
Perhaps we could make a proper go of this when i get back?

**Comment by liamjohnston** [comment]
Rowan and I are rebuilding it in react, check it:
https://github.com/InsaneWookie/rivl2/

Hasn't been a priority for either of us though

**Comment by deanoemcke** [comment]
@InsaneWookie you don't have time for this! you're supposed to be working on mame-highscores!

**Comment by InsaneWookie** [comment]
Haha I wanted something to learn React with. I'll get back onto mame-highscores one day. The arcade cabinet needs some love too

**Pull request merged**
